A = now()

MsgBox "FormatDateTime : " & FormatDateTime(A)
MsgBox "Day : " & Day(A)
MsgBox "Hour : " & Hour(A)
MsgBox "Minute : " & Minute(A)
MsgBox "Month : " & Month(A)
MsgBox "Second : " & Second(A)
MsgBox "WeekDay : " & WeekDay(A)
MsgBox "Year : " & Year(A)